### ISSUE TITLE
glc-play won't save video streams.

### ISSUE THREAD

**Issue by MalikuMane** [lano1106/glcs#14]
I've tried many different options and it seems that I can capture with glc-capture and play the video with glc-play but saving using -p -b or -y only creates completely black frames until forced to terminate. I've tried multiple revisions as far back as 37ddf9b1da0357865a8ae45e3037d8c891f5a289 which was the oldest one I could compile and the issue is still present.

**Comment by lano1106** [comment]
It might be broken. I have never really used the glc format as it creates HUGE files. I highly recommend using the ffmpeg pipe that encodes H.264 in any format you want, mp4, mkv, flv or whatever.

The really cool thing with ffmpeg is that it started to support HW encoders (wasn't there when I first released glcs). NVENC for Nvidia cards for instance.

ffmpeg can then help you to manipulate the capture movie anyway you want.

I'll take some time to look at it this week but note, that I was considering removing legacy GLC format support eventually down the road once the ffmpeg pipe solution gets more mature.

**Comment by MalikuMane** [comment]
I just don't care about this anymore.
