### ISSUE TITLE
Wrong shebang in build script

### ISSUE THREAD

**Issue by darkuranium** [lano1106/glcs#15]
The `build.sh` build script has `#!/bin/sh` at the start.

The code is, however, Bash (instead of "vanilla" Bourne Shell), and the script thus fails in Debian Wheezy (because Debian maps `sh` to its own `dash` shell).

The best solution would be to make the file Bourne-Shell-Compatible; this would also make it work in non-Linux systems (like FreeBSD).

**Comment by lano1106** [comment]
Sapein graciously fixed the issue.
